theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: TomÃ¡s Brito Devotos's CV
show_downloads: true #["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

github:
  zip_url: https://github.com/tomas-brito-devoto/CV/blob/gh-pages/20230410_CV_BritoDevoto-ENG.pdf
  tar_url: https://github.com/tomas-brito-devoto/CV/blob/gh-pages/20230410_CV_BritoDevoto-SPA.pdf
  another_url: 
