theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: TomÃ¡s Brito Devotos's CV
show_downloads: true #["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
